name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  terraform:
    name: terraform apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Init
      run: terraform -chdir=terraform init -backend-config=backend/prod.tfbackend

    - name: Terraform Plan
      id: terraform-plan
      run: terraform -chdir=terraform plan -var-file=vars/prod.tfvars

    - name: Confirmation Prompt
      id: confirmation
      run: |
        echo "::set-output name=confirm::$(echo 'no')"
        echo "Do you want to proceed with 'terraform apply'? (yes/no)"
        read confirmation
        if [[ "$confirmation" == "yes" ]]; then
          echo "::set-output name=confirm::$(echo 'yes')"
        fi
      shell: bash

    - name: Terraform Apply
      if: steps.confirmation.outputs.confirm == 'yes'
      run: terraform -chdir=terraform apply -var-file=vars/prod.tfvars -auto-approve
