name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      apply:
        description: 'Set to "true" to apply the Terraform module'
        required: true
        default: "false"
jobs:
  terraform:
    name: terraform apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Terraform Init
      run: terraform -chdir=terraform init -backend-config=backend/prod.tfbackend

    - name: Terraform Plan
      id: terraform-plan
      run: terraform -chdir=terraform plan -var-file=vars/prod.tfvars

    - name: Terraform Apply
      if: github.event.inputs.apply == 'true'
      run: terraform -chdir=terraform apply -var-file=vars/prod.tfvars -auto-approve
